### ISSUE TITLE
Criar tela de relatório por paciente

### ISSUE THREAD

**Issue by wellingtonT** [nucleotec/cirurgiaSegura#3]
Criar um menu na página de relatórios - Cirurgias por paciente.

Essa página deverá conter um formulário com as seguintes informações: CPF ou Nome do paciente e período de datas a serem pesquisadas.

Essa pesquisa deverá retornar uma tabela com todas as cirurgias do paciente em questão. Dados ta tabela: Nome do paciente - Nomes dos médicos - Data da cirurgia - Botão para detalhamento

**Comment by nucleotec** [comment]
Branch: issue#03
